### ISSUE TITLE
Input mdp file not working

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_md#26]
The optional parameter input_mdp_file is not working unless you also put it as a property:

prop = {
    'gmxlib' : gmxlib_dir,
    **'input_mdp_path' : mdp_em,**  **<-- Shouldn't be needed** 
    'remove_tmp' : False
}

Grompp(input_gro_path=gro, 
       input_top_zip_path=top, 
       **input_mdp_path= mdp_em,** **<-- Not working without the previous property**
       input_ndx_path= ndx,
       output_tpr_path=output_gppmin_tpr,  
       properties=prop).launch()

**Comment by PauAndrio** [comment]
Solved in v3.5.1
