### ISSUE TITLE
input_ndx input in genrestr bb shouldn't be mandatory

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_md#27]
input_ndx input in genrestr bb shouldn't be mandatory, please convert it to optional input. Thanks!

**Comment by PauAndrio** [comment]
Closed, available in the 2020.4 release.


commit d889c849d6f4335c4d0f9c73c18575603e4a0cdd (HEAD -> docstring, origin/docstring)
Author: Pau Andrio <andriopau@gmail.com>
Date:   Mon Dec 14 20:22:45 2020 +0100

    feat(genrestr): Changing input_ndx_path from a required argument to an optional one.

    Closes https://github.com/bioexcel/biobb_md/issues/27
