### ISSUE TITLE
gmx grompp simulation_type for ions

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_md#32]
[gmx_grompp](https://biobb-md.readthedocs.io/en/latest/gromacs.html#module-gromacs.grompp) bb admits different preconfigured simulation types through the **_simulation_type_** property: minimization, nvt, npt, etc. For adding ions we typically use the **minimization** one, which is quite strange (and confusing). It would be good to add a new simulation_type named **"ions"**, using the same mdp preconfigured file as the minimization one. Just changing the name to avoid the possible confusion.

**Comment by PauAndrio** [comment]
Testing
