### ISSUE TITLE
pdb2gmx doest not trigger a warning when unknown properties are used

### ISSUE THREAD

**Issue by PauAndrio** [bioexcel/biobb_md#38]
Could not replicate (Check second property), please provide a replicable example.

```
pdb2gmx:
  paths:
    input_pdb_path: file:test_data_dir/gromacs/egfr.pdb
    output_gro_path: output_gro.gro
    output_top_zip_path: output_top_zip.zip
    ref_output_top_zip_path: file:test_reference_dir/gromacs/ref_pdb2gmx.zip
    ref_output_gro_path: file:test_reference_dir/gromacs/ref_pdb2gmx.gro
  properties:
    his: 0 0 1 1 0 0 0
    prova: Noexisteix
```

-------------------------------------------------------------------------------

```
>>> nosetests -s -v biobb_md/test/unitests/test_gromacs/test_pdb2gmx.py
test_pdb2gmx.TestPdb2gmx.test_pdb2gmx ... /Users/pau/projects/biobb_common/biobb_common/tools/file_utils.py:354: UserWarning: Warning: prova is not a recognized property. The most similar property is: path
  error_property, close_property))
Checking if empty file: /private/tmp/biobb/unitests/pdb2gmx/output_top_zip.zip
```

**Comment by gbayarri** [comment]
I think it triggers the warning. Check the output of nosetest:

nosetests -s -v biobb_md/test/unitests/test_gromacs/test_pdb2gmx.py
test_pdb2gmx.TestPdb2gmx.test_pdb2gmx ... /Users/pau/projects/biobb_common/biobb_common/tools/file_utils.py:354: **UserWarning: Warning: prova is not a recognized property. The most similar property is: path**
  error_property, close_property))
Checking if empty file: /private/tmp/biobb/unitests/pdb2gmx/output_top_zip.zip
