### ISSUE TITLE
Problem with Gmx version check

### ISSUE THREAD

**Issue by adamhospital** [bioexcel/biobb_md#48]
https://github.com/bioexcel/biobb_md/blob/2844840ba23e7da6607d4022f9c3919d37e5bb79/biobb_md/gromacs/mdrun.py#L207-L211

When using mpi_bin and not using containers (e.g. in any supercomputer with gromacs installed), the code snippet checking gromacs version is crashing because self.gmx_version is not initialized (see lines 122 and 123). https://github.com/bioexcel/biobb_md/blob/2844840ba23e7da6607d4022f9c3919d37e5bb79/biobb_md/gromacs/mdrun.py#L122-L123

Possible solution is to just add `and not self.mpi_bin`to the line 208.

**Comment by PauAndrio** [comment]
Solved in 3.7.1
