### ISSUE TITLE
Add 'dev' attribute for each building block

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_md#51]
Hi all,

I'm trying to develop a workflow with these libraries, but I keep finding myself needing extra command line options that're not supported. This is to be expected as there're a ton of available tools, with a ton of options and they're only going to get even more numerous.

So that's why I think that the `dev` attribute of the `mdrun` building block is necessary to support real-life workflows. Currently I'm patching the code to add it on each class where I need it, but it'd be nice to have the extra flexibility, at the developer's responsibility.

Thanks.

**Comment by PauAndrio** [comment]
Hi!

That's a very good idea! I have implemented this feature in the biobb_common generic object, so right now every block has the `dev` option. The downside is that this new features will not be in the conda installer until the next release (v3.8). As an advanced user I recommend you to download (clone) the [git version of biobb_common](https://github.com/bioexcel/biobb_common) and use that one to benefit from the latest features.

Regards,
Pau Andrio
